deps_config := \
	test/overlay/Kconfig \
	test/optee/Kconfig \
	test/env/Kconfig \
	test/dm/Kconfig \
	test/Kconfig \
	lib/optee/Kconfig \
	lib/efi_loader/Kconfig \
	lib/efi/Kconfig \
	lib/crypto/Kconfig \
	lib/rsa/Kconfig \
	lib/dhry/Kconfig \
	lib/Kconfig \
	fs/yaffs2/Kconfig \
	fs/cramfs/Kconfig \
	fs/ubifs/Kconfig \
	fs/jffs2/Kconfig \
	fs/fat/Kconfig \
	fs/reiserfs/Kconfig \
	fs/ext4/Kconfig \
	fs/cbfs/Kconfig \
	fs/btrfs/Kconfig \
	fs/Kconfig \
	drivers/watchdog/Kconfig \
	drivers/w1-eeprom/Kconfig \
	drivers/w1/Kconfig \
	drivers/virtio/Kconfig \
	drivers/video/imx/Kconfig \
	drivers/video/bridge/Kconfig \
	drivers/video/stm32/Kconfig \
	drivers/video/rockchip/Kconfig \
	drivers/video/meson/Kconfig \
	drivers/video/fonts/Kconfig \
	drivers/video/Kconfig \
	drivers/ufs/Kconfig \
	drivers/usb/eth/Kconfig \
	drivers/usb/gadget/Kconfig \
	drivers/usb/ulpi/Kconfig \
	drivers/usb/phy/Kconfig \
	drivers/usb/emul/Kconfig \
	drivers/usb/musb-new/Kconfig \
	drivers/usb/musb/Kconfig \
	drivers/usb/dwc3/Kconfig \
	drivers/usb/cdns3/Kconfig \
	drivers/usb/host/Kconfig \
	drivers/usb/Kconfig \
	drivers/tpm/Kconfig \
	drivers/timer/Kconfig \
	drivers/thermal/Kconfig \
	drivers/tee/optee/Kconfig \
	drivers/tee/Kconfig \
	drivers/sysreset/Kconfig \
	drivers/spmi/Kconfig \
	drivers/spi/Kconfig \
	drivers/soc/ti/Kconfig \
	drivers/soc/Kconfig \
	drivers/sound/Kconfig \
	drivers/smem/Kconfig \
	drivers/serial/Kconfig \
	drivers/scsi/Kconfig \
	drivers/rtc/Kconfig \
	drivers/reset/Kconfig \
	drivers/remoteproc/Kconfig \
	drivers/ram/stm32mp1/Kconfig \
	drivers/ram/rockchip/Kconfig \
	drivers/ram/Kconfig \
	drivers/qe/Kconfig \
	drivers/pwm/Kconfig \
	drivers/power/regulator/Kconfig \
	drivers/power/pmic/Kconfig \
	drivers/power/domain/Kconfig \
	drivers/power/Kconfig \
	drivers/pinctrl/uniphier/Kconfig \
	drivers/pinctrl/rockchip/Kconfig \
	drivers/pinctrl/renesas/Kconfig \
	drivers/pinctrl/nxp/Kconfig \
	drivers/pinctrl/mvebu/Kconfig \
	drivers/pinctrl/mtmips/Kconfig \
	drivers/pinctrl/mscc/Kconfig \
	drivers/pinctrl/meson/Kconfig \
	drivers/pinctrl/mediatek/Kconfig \
	drivers/pinctrl/exynos/Kconfig \
	drivers/pinctrl/broadcom/Kconfig \
	drivers/pinctrl/Kconfig \
	drivers/phy/marvell/Kconfig \
	drivers/phy/allwinner/Kconfig \
	drivers/phy/Kconfig \
	drivers/pch/Kconfig \
	drivers/pci_endpoint/Kconfig \
	drivers/pci/Kconfig \
	drivers/nvme/Kconfig \
	drivers/net/mscc_eswitch/Kconfig \
	drivers/net/ti/Kconfig \
	drivers/net/fsl-mc/Kconfig \
	drivers/net/pfe_eth/Kconfig \
	drivers/net/phy/Kconfig \
	drivers/net/Kconfig \
	drivers/mtd/ubi/Kconfig \
	drivers/mtd/spi/Kconfig \
	drivers/mtd/nand/spi/Kconfig \
	drivers/mtd/nand/raw/Kconfig \
	drivers/mtd/nand/Kconfig \
	drivers/mtd/Kconfig \
	drivers/mmc/Kconfig \
	drivers/misc/Kconfig \
	drivers/memory/Kconfig \
	drivers/mailbox/Kconfig \
	drivers/led/Kconfig \
	drivers/input/Kconfig \
	drivers/i2c/muxes/Kconfig \
	drivers/i2c/Kconfig \
	drivers/hwspinlock/Kconfig \
	drivers/gpio/Kconfig \
	drivers/fpga/Kconfig \
	drivers/firmware/Kconfig \
	drivers/fastboot/Kconfig \
	drivers/dma/ti/Kconfig \
	drivers/dma/Kconfig \
	drivers/dfu/Kconfig \
	drivers/ddr/fsl/Kconfig \
	drivers/board/Kconfig \
	drivers/demo/Kconfig \
	drivers/ddr/imx/imx8m/Kconfig \
	drivers/ddr/imx/Kconfig \
	drivers/ddr/altera/Kconfig \
	drivers/ddr/Kconfig \
	drivers/crypto/fsl/Kconfig \
	drivers/crypto/Kconfig \
	drivers/cpu/Kconfig \
	drivers/clk/uniphier/Kconfig \
	drivers/clk/tegra/Kconfig \
	drivers/clk/sifive/Kconfig \
	drivers/clk/sunxi/Kconfig \
	drivers/clk/renesas/Kconfig \
	drivers/clk/owl/Kconfig \
	drivers/clk/mvebu/Kconfig \
	drivers/clk/meson/Kconfig \
	drivers/clk/imx/Kconfig \
	drivers/clk/exynos/Kconfig \
	drivers/clk/at91/Kconfig \
	drivers/clk/analogbits/Kconfig \
	drivers/clk/Kconfig \
	drivers/cache/Kconfig \
	drivers/bootcount/Kconfig \
	drivers/block/Kconfig \
	drivers/axi/Kconfig \
	drivers/ata/Kconfig \
	drivers/adc/Kconfig \
	drivers/core/Kconfig \
	drivers/Kconfig \
	net/Kconfig \
	env/Kconfig \
	dts/Kconfig \
	disk/Kconfig \
	cmd/ti/Kconfig \
	cmd/mvebu/Kconfig \
	lib/efi_selftest/Kconfig \
	cmd/Kconfig \
	common/spl/Kconfig \
	common/Kconfig \
	api/Kconfig \
	arch/arm/Kconfig.debug \
	board/samsung/jz2440/Kconfig \
	arch/arm/Kconfig \
	arch/Kconfig \
	Kconfig

include/config/auto.conf: \
	$(deps_config)

ifneq "$(UBOOTVERSION)" "2020.01"
include/config/auto.conf: FORCE
endif

$(deps_config): ;
